### ISSUE TITLE
main_fcs/main_fcs_csv

### ISSUE THREAD

**Issue by singha53-zz** [nolanlab/NeighborhoodCoordination#3]
Hi, 

I am re-running the tensor decomposition notebook which uses 'main_fcs_csv.csv'. The repo points to mendely for the data. The file that is downloaded is called CRC_clusters_neighborhoods_markers.csv. Can you clarify if this is the same as main_fcs/main_fcs_csv or is that somewhere else?

Thanks,
Amrit

**Comment by gorkemkose** [comment]
If you click on "Download All 87 MB" in [this](https://data.mendeley.com/datasets/mpjzbtfgfr/1) link, and unzip the downloaded zip file, there is a file named main_fcs_csv.csv inside. But the CRC_clusters_neighborhoods_markers.csv is the very same file I believe.

**Comment by salilb1** [comment]
Hi there, sorry for the delayed response - I didn't receive a notification here. 

Please check the tensor_decomposition_cleaned_up notebook. That starts from the Mendeley file (cells2_salil) is the same.

Salil
